### ISSUE TITLE
개발 공부 4일차, 네이버 서버 생성, node.js 

### ISSUE THREAD

**Issue by wonny1212** [wonny1212/2020#4]
Node.js 서버 환경에서 작동하는 자바스크립트
https://cyberx.tistory.com/135

NPM
Node Packaged Modules
노드 패키지 매니저는 다양한 패키지 모듈을 제공함

----------------------------
https://blog.naver.com/nieah914/221609709142
네이버 서버 생성

**Comment by wonny1212** [comment]
https://blog.lael.be/post/1721
센토스 서버 세팅

0. passwd root 비번 바꾸기
1. update
2. date
------------------------------------------------------------------------
node.js 설치
curl -sL https://rpm.nodesource.com/setup_10.x | sudo bash -
------------------------------------
curl 명령어: 리눅스에서 http 메세지를 쉘에서 요청하여 결과를 확인 하는 명령어
http 경로의 데이터를 가져온다
curl [옵션] [URL]

https://goddaehee.tistory.com/83
리눅스 명령어 
----------------------------------
sudo yum install nodejs

node --version
npm --version

git 클론

해당 폴더에서 npm install
해당 폴더에서 명령어 node app.js

**Comment by wonny1212** [comment]
yum install nodejs


[root@wonny ~]# yum install nodejs
Loaded plugins: fastestmirror, security
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: mirror.kakao.com
 * extras: mirror.kakao.com
 * updates: mirror.kakao.com
No package nodejs available.
Error: Nothing to do

**Comment by wonny1212** [comment]
[root@wonny ~]# curl -sL https://rpm.nodesource.com/setup_10.x | sudo bash -

## Installing the NodeSource Node.js 10.x repo...


## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## Confirming "el6-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_10.x/el/6/x86_64/nodesource-release-el6-1.noarch.rpm'

## Downloading release setup RPM...

+ mktemp
+ curl -sL -o '/tmp/tmp.fxtIlsFApG' 'https://rpm.nodesource.com/pub_10.x/el/6/x86_64/nodesource-release-el6-1.noarch.rpm'

## Installing release setup RPM...

+ rpm -i --nosignature --force '/tmp/tmp.fxtIlsFApG'

## Cleaning up...

+ rm -f '/tmp/tmp.fxtIlsFApG'

## Checking for existing installations...

+ rpm -qa 'node|npm' | grep -v nodesource

## Run `sudo yum install -y nodejs` to install Node.js 10.x and npm.
## You may also need development tools to build native addons:
     sudo yum install gcc-c++ make
## To install the Yarn package manager, run:
     curl -sL https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo
     sudo yum install yarn


위에꺼는 다운로드 받은 것

**Comment by wonny1212** [comment]
[root@wonny ~]# sudo yum install nodejs
Loaded plugins: fastestmirror, security
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: mirror.kakao.com
 * extras: mirror.kakao.com
 * updates: mirror.kakao.com
nodesource                                            | 2.5 kB     00:00
nodesource/primary_db                                 |  42 kB     00:00
Resolving Dependencies
--> Running transaction check
---> Package nodejs.x86_64 2:10.18.1-1nodesource will be installed
--> Finished Dependency Resolution

Dependencies Resolved

=============================================================================
 Package     Arch        Version                       Repository       Size
=============================================================================
Installing:
 nodejs      x86_64      2:10.18.1-1nodesource         nodesource       20 M

Transaction Summary
=============================================================================
Install       1 Package(s)

Total download size: 20 M
Installed size: 61 M
Is this ok [y/N]: y
Downloading Packages:
nodejs-10.18.1-1nodesource.x86_64.rpm                 |  20 MB     00:00
warning: rpmts_HdrFromFdno: Header V4 RSA/SHA512 Signature, key ID 34fa74dd: NOKEY
Retrieving key from file:///etc/pki/rpm-gpg/NODESOURCE-GPG-SIGNING-KEY-EL
Importing GPG key 0x34FA74DD:
 Userid : NodeSource <gpg-rpm@nodesource.com>
 Package: nodesource-release-el6-1.noarch (installed)
 From   : /etc/pki/rpm-gpg/NODESOURCE-GPG-SIGNING-KEY-EL
Is this ok [y/N]: y
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
Warning: RPMDB altered outside of yum.
  Installing : 2:nodejs-10.18.1-1nodesource.x86_64                       1/1
  Verifying  : 2:nodejs-10.18.1-1nodesource.x86_64                       1/1

Installed:
  nodejs.x86_64 2:10.18.1-1nodesource

Complete!

**Comment by wonny1212** [comment]
[root@wonny ~]# node --version
v10.18.1
[root@wonny ~]# ^C
[root@wonny ~]# npm --version
6.13.4
[root@wonny ~]#

**Comment by wonny1212** [comment]
node.js 테스트 해보기
https://kdydesign.github.io/2017/07/15/nodejs-npm-tutorial/

**Comment by wonny1212** [comment]
[root@wonny ~]# cat >main.js
function sum(a,b){
return a+b;
}
console.log('summ = '+sum(2,3));
---------------------------------
cat > file1 (내용을 입력하고 ctrl + d를 눌러 저장한다.)
https://withcoding.com/109
---------------------------------
[root@wonny ~]# ls
anaconda-ks.cfg  install.log  install.log.syslog  main.js
[root@wonny ~]# node main.js
summ = 5

**Comment by wonny1212** [comment]
[root@wonny NodeTest]# npm init -y
Wrote to /usr/local/bin/NodeTest/package.json:

{
  "name": "NodeTest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


[root@wonny NodeTest]# npm install
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN NodeTest@1.0.0 No description
npm WARN NodeTest@1.0.0 No repository field.

up to date in 0.424s
found 0 vulnerabilities

[root@wonny NodeTest]# ls
package.json  package-lock.json
[root@wonny NodeTest]#


https://kdydesign.github.io/2017/07/15/nodejs-npm-tutorial/

**Comment by wonny1212** [comment]
git clone http://github.com/SeyoungKwon1986/nugu-play-sample-source.git


설치 오류시
yum update -y mss curl

**Comment by wonny1212** [comment]
Server is running on 3000 port
::ffff:210.121.202.16 - - [14/Jan/2020:08:56:28 +0000] "GET /nugu HTTP/1.1" 404 1279
Error: Not Found
    at app.use (/home/nbpmon/nugu-play-sample-source/app.js:19:15)
    at Layer.handle [as handle_request] (/home/nbpmon/nugu-play-sample-source/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/nbpmon/nugu-play-sample-source/node_modules/express/lib/router/index.js:317:13)
    at /home/nbpmon/nugu-play-sample-source/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/nbpmon/nugu-play-sample-source/node_modules/express/lib/router/index.js:335:12)
    at next (/home/nbpmon/nugu-play-sample-source/node_modules/express/lib/router/index.js:275:10)
    at /home/nbpmon/nugu-play-sample-source/node_modules/express/lib/router/index.js:635:15
    at next (/home/nbpmon/nugu-play-sample-source/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/home/nbpmon/nugu-play-sample-source/node_modules/express/lib/router/index.js:174:3)
    at router (/home/nbpmon/nugu-play-sample-source/node_modules/express/lib/router/index.js:47:12)

----------------------------------
http://27.96.135.60:3000/nugu

Error: Not Found
    at app.use (/home/nbpmon/nugu-play-sample-source/app.js:19:15)
    at Layer.handle [as handle_request] (/home/nbpmon/nugu-play-sample-source/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/nbpmon/nugu-play-sample-source/node_modules/express/lib/router/index.js:317:13)
    at /home/nbpmon/nugu-play-sample-source/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/nbpmon/nugu-play-sample-source/node_modules/express/lib/router/index.js:335:12)
    at next (/home/nbpmon/nugu-play-sample-source/node_modules/express/lib/router/index.js:275:10)
    at /home/nbpmon/nugu-play-sample-source/node_modules/express/lib/router/index.js:635:15
    at next (/home/nbpmon/nugu-play-sample-source/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/home/nbpmon/nugu-play-sample-source/node_modules/express/lib/router/index.js:174:3)
    at router (/home/nbpmon/nugu-play-sample-source/node_modules/express/lib/router/index.js:47:12)
-----------------------

**Comment by wonny1212** [comment]
노드에서 크게 3가지로 모듈을 분류할 수 있다.

**1. 내장 모듈 ( fs , util, url 등..)**
```
var url = require("url");
var parsedURL = url.parse("http://www.example.com/profile?name=barry");
 
console.log(parsedURL.protocol); // "http:"
console.log(parsedURL.host); // "www.example.com"
console.log(parsedURL.query); // "name=barry"
```
내장모듈 url을 require로 불러와서 그 개체의 parse 함수를 이용해 url에서 정보를 추출했다.


**2. npm으로 불러온 서드파티 모듈(passport, mongoose 등..)**

```
var express = require("express"); //Express를 변수에 담는다.
var app = express();//Express를 호출하고 새로운 Express 애플리케이션을 변수(app)에 넣음
 

app.get("/",function(request, response){
    response.send("Hello World"); // HelloWorld를 전송한다.
});
 
app.listen(3000, function(){
    console.log("Express app started on port 3000.");
    //3000번 포트에서 Express서버를 시작하고 시작했다는 로그 기록
});

```
npm install express --save 를 입력해서 설치하고 위 소스를 돌리면 잘 실행된다.

* npm으로 다운받아 설치할 수 있는 모듈이 어떤것이 있는지 궁금하고 사용방법이 궁금하다면

https://www.npmjs.com/ << 여기서 검색해보면 된다.

https://npms.io/ <<여기서는 설치하려는 모듈이 얼마나 안정적이고 유명한지를 별점을 통해 알 수 있다.






**3. 사용자 정의 모듈** 
```

var MAX = 100;
function randomInteger(){
  return Math.floor((Math.random() * MAX));
}
module.exports = randomInteger;
//다른 파일에 모듈 노출
```

이 코드를 random-integer.js 라는 파일에 적어 만들었다.

module.exports를 이용해 모듈을 내보낸다.

* module.exports 에는 변수에 할당할 수 있는 모든 것을 할당할 수 있다. 여기서는 함수를 할당 했지만 보통 개체를 할당한다.

```
var randomInt = require("./random-integer"); //상대경로
console.log(randomInt()); // 15
console.log(randomInt()); // 27
console.log(randomInt()); // 67

```
다른 자바스크립트파일에서 위와 같이 require로 해당 파일 요청해서 모듈을 사용한다.

출처: https://jeong-pro.tistory.com/58?category=790237 [기본기를 쌓는 정아마추어 코딩블로그]

**Comment by wonny1212** [comment]
app.js  config.js  LICENSE  nugu  package.json  README.md  routes

-----install npm---------------

app.js     LICENSE       nugu          package-lock.json  routes
config.js  node_modules  package.json  README.md
---------------------------

node_modules 가 추가 됨
