### ISSUE TITLE
7일 nodejs 서버에 띄우기

### ISSUE THREAD

**Issue by wonny1212** [wonny1212/2020#9]
1. 네이버 서버에 간단하게 테스트 하기.

[root@wonny ~]# cat> a.js

```
var request = require('request');

request.get({url: 'http://www.tistory.com'}, function(err,response, body){
console.log(body);
```

그냥은 실행 안된다. 모듈 설치를 해줘야 한다.
npm install --save request
해주고
node a.js 해야함

그러면 저 내용이 가져와짐

궁금증: git에서 다운 받을경우 모듈설치를 하지 않아도 서버가 잘 작동하는데
왜 간단한 테스트로 글을 작성하면 안되고, 모듈을  설치해야 작동이 되는거지?

궁금증에 대한 답:
바로 package.json 파일에 dependencies 프로퍼티에 모듈들이 정의되어 있습니다.
이 모듈들은 express-generator가 생성해준 것입니다.
npm install명령어를 실행하면, package.json 파일의 dependencies 프로퍼티를 보고 모듈을 설치합니다.
즉, dependencies 에는 모듈을 사용하겠다고 선언만 한 것이고, 진짜로 설치를 하려면 npm install을 해주어야 합니다.
![image](https://user-images.githubusercontent.com/48310694/73076280-25ce0f80-3f01-11ea-8a4f-14815016ddd9.png)
출처: https://victorydntmd.tistory.com/23
-------------------------------------------------------------------------------------------------------------

https://medium.com/harrythegreat/node-js%EC%97%90%EC%84%9C-request-js-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0-28744c52f68d
https://dalkomit.tistory.com/104

**Comment by wonny1212** [comment]
위처럼 보면 사람이 보기에 부적절 이쁘게 보려면
Cheerio 모듈!

```
var request = require('request');
var cheerio = require('cheerio');

request.get({url: 'http://www.tistory.com'}, function(err,response, body){
//console.log(body);
var $ = cheerio.load(body);
var arr = $('.tistory_recomm').children('.recomm_blog').children('.tit_subject');
for(var i=0; i<arr.prevObject.length; i++){
console.log(arr.preObject[i].children[0].next.children[3].children[0].data);
}
})
```
Error: Cannot find module 'cheerio'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/a.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

이렇게 오류가 뜬다.
npm install --save cheerio
node a.js 

아무일도 일어나지 않는다


https://tistory.lyasee.com/15
를 참고해서 부분을 수정해야한다
```
const request = require('request');
const cheerio = require('cheerio');

request('http://tistory.com', function (error, response, body) {
    if(error) throw error
    
    $ = cheerio.load(body); // request모듈을 이용해서 가져온정보를 넣어줌
    
    let json = [], title, writer
    $('#mArticle > div.tistory_recomm > div.recomm_blog').each(function(index, ele){ // <div class="recomm_blog">를 반복
        title = $(this).find('a > .tit_subject').text() // a태그 아래에 class="tit_subject"의 텍스트(제목)
        writer = $(this).find('a > .txt_writer').text() // a태그 아래에 class="txt_writer"의 텍스트(작성자)
        json.push({ title: title, writer: writer })
    });

    console.log('json: ', json);
});
```

안나온다.. 더 읽어본다

[root@wonny ~]# cat a.js
```
const request = require('request');
const cheerio = require('cheerio');

request('http://tistory.com', function (error, response, body) {
    if(error) throw error

    $ = cheerio.load(body); // request모듈을 이용해서 가져온정보를 넣어줌

    let json = [], title, writer
    $('#daumFoot > div > div.question_tistory > div:nth-child(2) > ul > li:nth-child(1)').each(function(index, ele){ // <div class="recomm_blog">를 반복
        title = $(this).find('.link_txt').text() // a태그 아래에 class="tit_subject"의 텍스트(제목)
       // writer = $(this).find('a > .txt_writer').text() // a태그 아래에 class="txt_writer"의 텍스트(작성자)
        json.push({ title: title})
    });

    console.log('json: ', json);
});
```
[root@wonny ~]# node a.js
json:  [ { title: '스킨' } ]
![image](https://user-images.githubusercontent.com/48310694/73063789-f6a8a580-3ee2-11ea-9876-09eccb5e708f.png)
![image](https://user-images.githubusercontent.com/48310694/73063852-1d66dc00-3ee3-11ea-914b-b88dc57d343d.png)

성공!!!
